#server:
#  port: 8081
##  error:
##    whitelabel:
##      enabled: false
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/DB_REGISTER_EMPLOYE?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    password: felipe
#    username: felipe
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
##  mvc:
##    throw-exception-if-no-handler-found: true
##  web:
##    resources:
##      add-mappings: false
#
#jwt:
#  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
